### ISSUE TITLE
Exam completion on cancel

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#18]
If you hit complete, fill the required data/comment, and hit Cancel. It still completes the exam.

**Comment by samibrix** [comment]
I have never seen this before can you recreate the issue, send me the steps please. Thanks!

**Comment by schinnagudi** [comment]
Hi Zafar,

Let me if these are the right steps you followed.

1. XR exam is loaded in radexammggmt.exe and you started the exam.

2. When you hit complete - XR Tech comments window pops up and followed by Bill only association. 
Here - 
You select required/Not Required data in Tech comments window and click cancel. 
Upon Cancelling - 'bill only' window pops up, you cancel this window as well....

Now we back on exammgmgt window and see the exam gets Completed.

**Reason why it is completed **- Since Tech has clicked on Exam 'Complete' Button and while doing so knows exam is completed only need to enter tech comments.

**We see 'Cancel' button on Tech comm and Bill only Windows why?** - For An exam if Tech wishes not to select any value, Tech cancel the window and move to Next step in the window.

**What If Tech Could accidentally hits Complete button?** - We should be educating them on this... Even after education this happens, We can change the Order status back to 
"Ordered" from back end  CCL..

Hope this clarifies

**Comment by samibrix** [comment]
Eugene, thank you for clarifying 
Zafar, the fact that you see tech comment and bill only pop up automatically that means you have completed the order, and t he cancel button is for cancelling the comments or selection of the bill only but not the Order. I hope this helps. Thanks!

**Comment by zafar2zafar** [comment]
Closing
